# Generated by Django 5.2.17 on 2026-10-03 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ok", models.BooleanField(default=False)),
                ("result", models.CharField(max_length=40)),
                ("student_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name": "Обращение формы заявок",
                "verbose_name_plural": "Обращения формы заявок",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rev", models.BigIntegerField(default=0)),
                ("epoch", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Состояние базы",
                "verbose_name_plural": "Состояние базы",
            },
        ),
        migrations.CreateModel(
            name="Tombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection", models.CharField(max_length=20)),
                ("doc_id", models.CharField(max_length=64)),
                ("rev", models.BigIntegerField(db_index=True)),
            ],
            options={
                "verbose_name": "Удалённая запись",
                "verbose_name_plural": "Удалённые записи",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("mentor", "Ментор"),
                            ("partner", "Партнёр"),
                        ],
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "link_id",
                    models.CharField(
                        blank=True,
                        help_text="Для ментора и администратора — запись из списка команды, для партнёра — запись партнёра",
                        max_length=64,
                        verbose_name="Связанная запись",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ",
                "verbose_name_plural": "Доступы",
            },
        ),
        migrations.CreateModel(
            name="Doc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.CharField(max_length=20, verbose_name="Коллекция"),
                ),
                (
                    "doc_id",
                    models.CharField(max_length=64, verbose_name="Идентификатор"),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Данные")),
                ("rev", models.BigIntegerField(db_index=True, verbose_name="Ревизия")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменён"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто изменил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("collection", "doc_id"), name="doc_unique"
                    )
                ],
            },
        ),
    ]
