# Generated by Django 5.2.17 on 2026-09-30 18:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Старт"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Окончание обучения"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Идёт набор / обучение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Поток",
                "verbose_name_plural": "Потоки",
                "ordering": ["-start_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "promo_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Промокод"
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True,
                        help_text="Заявки с этим utm_source автоматически привяжутся к партнёру",
                        max_length=100,
                        verbose_name="utm_source",
                    ),
                ),
                (
                    "share_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        max_digits=5,
                        verbose_name="Доля партнёра, %",
                    ),
                ),
                (
                    "contacts",
                    models.TextField(blank=True, verbose_name="Контакты / реквизиты"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Если указать — партнёр сможет входить и видеть отчёт по своему трафику",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учётная запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Партнёр",
                "verbose_name_plural": "Партнёры",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartnerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата выплаты",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="crm.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выплата партнёру",
                "verbose_name_plural": "Выплаты партнёрам",
                "ordering": ["-paid_date"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Телефон"),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Telegram"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Город"),
                ),
                (
                    "consent_pd",
                    models.BooleanField(
                        default=False, verbose_name="Согласие на обработку ПД"
                    ),
                ),
                (
                    "partner_share_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Фиксируется при привязке партнёра, чтобы смена условий не пересчитывала старые сделки",
                        max_digits=5,
                        verbose_name="Доля партнёра, %",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="utm_source"
                    ),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="utm_campaign"
                    ),
                ),
                (
                    "promo_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Промокод"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "Новая заявка"),
                            ("contacted", "Связались"),
                            ("call", "Созвон"),
                            ("waiting_payment", "Ждём оплату"),
                            ("studying", "Обучается"),
                            ("final_project", "Итоговый проект"),
                            ("job_search", "Поиск работы"),
                            ("offer", "Оффер"),
                            ("probation_passed", "Прошёл испытательный"),
                            ("lost", "Отказ / выбыл"),
                        ],
                        default="new",
                        max_length=30,
                        verbose_name="Этап",
                    ),
                ),
                (
                    "stage_changed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Этап изменён"
                    ),
                ),
                (
                    "lost_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Причина отказа / выбытия",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Итоговая цена по договору с учётом скидок",
                        max_digits=12,
                        null=True,
                        verbose_name="Стоимость обучения",
                    ),
                ),
                (
                    "job_company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Компания (оффер)"
                    ),
                ),
                (
                    "job_position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Должность"
                    ),
                ),
                (
                    "job_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Зарплата на оффере",
                    ),
                ),
                (
                    "offer_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата оффера"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создан"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="crm.cohort",
                        verbose_name="Поток",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ментор",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="crm.partner",
                        verbose_name="Партнёр (источник)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "Новая заявка"),
                            ("contacted", "Связались"),
                            ("call", "Созвон"),
                            ("waiting_payment", "Ждём оплату"),
                            ("studying", "Обучается"),
                            ("final_project", "Итоговый проект"),
                            ("job_search", "Поиск работы"),
                            ("offer", "Оффер"),
                            ("probation_passed", "Прошёл испытательный"),
                            ("lost", "Отказ / выбыл"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "to_stage",
                    models.CharField(
                        choices=[
                            ("new", "Новая заявка"),
                            ("contacted", "Связались"),
                            ("call", "Созвон"),
                            ("waiting_payment", "Ждём оплату"),
                            ("studying", "Обучается"),
                            ("final_project", "Итоговый проект"),
                            ("job_search", "Поиск работы"),
                            ("offer", "Оффер"),
                            ("probation_passed", "Прошёл испытательный"),
                            ("lost", "Отказ / выбыл"),
                        ],
                        max_length=30,
                    ),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="crm.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена этапа",
                "verbose_name_plural": "История этапов",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Сумма"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Срок оплаты")),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата оплаты"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Ожидается"),
                            ("paid", "Оплачен"),
                            ("cancelled", "Отменён"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Способ оплаты"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Комментарий"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="crm.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="crm.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заметка",
                "verbose_name_plural": "Заметки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200, verbose_name="Компания")),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Вакансия"
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Ссылка")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Отклик"),
                            ("hr", "Скрининг HR"),
                            ("test", "Тестовое"),
                            ("interview", "Собеседование"),
                            ("offer", "Оффер"),
                            ("accepted", "Оффер принят"),
                            ("rejected", "Отказ"),
                        ],
                        default="applied",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Зарплата",
                    ),
                ),
                (
                    "applied_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Дата отклика",
                    ),
                ),
                (
                    "interview_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Собеседование"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="crm.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отклик",
                "verbose_name_plural": "Отклики и собеседования",
                "ordering": ["-applied_date", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["stage"], name="crm_student_stage_03d80a_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["created_at"], name="crm_student_created_993a39_idx"
            ),
        ),
    ]
