# Generated by Django 5.2.17 on 2026-10-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Заполняется при импорте резервной копии, чтобы не создавать дубли",
                max_length=64,
                verbose_name="ID в веб-версии",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Заполняется при импорте резервной копии, чтобы не создавать дубли",
                max_length=64,
                verbose_name="ID в веб-версии",
            ),
        ),
        migrations.AddField(
            model_name="partnerpayout",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Заполняется при импорте резервной копии, чтобы не создавать дубли",
                max_length=64,
                verbose_name="ID в веб-версии",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Заполняется при импорте резервной копии, чтобы не создавать дубли",
                max_length=64,
                verbose_name="ID в веб-версии",
            ),
        ),
    ]
