# Generated by Django 5.2.17 on 2026-10-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_external_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="next_step",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Следующий шаг"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="next_step_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата следующего шага"
            ),
        ),
    ]
