# Generated by Django 5.2.17 on 2026-10-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_next_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="cohort",
            name="modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Список модулей вида [{"id": "m1", "title": "Введение"}]. Переносится из веб-версии.',
                verbose_name="Программа",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="progress",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Идентификатор модуля потока → дата, когда он отмечен пройденным",
                verbose_name="Пройденные модули",
            ),
        ),
    ]
