# Generated by Django 5.2.17 on 2026-10-02 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_program_progress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("call", "Созвон"),
                            ("lesson", "Занятие"),
                            ("consult", "Консультация"),
                            ("other", "Другое"),
                        ],
                        default="call",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Запланирована"),
                            ("done", "Состоялась"),
                            ("missed", "Не состоялась"),
                            ("cancelled", "Отменена"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="Время")),
                (
                    "duration_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Длительность, мин"
                    ),
                ),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="Ссылка"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                (
                    "external_id",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=64
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="crm.cohort",
                        verbose_name="Поток",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто проводит",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meetings",
                        to="crm.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Встреча",
                "verbose_name_plural": "Встречи",
                "ordering": ["date", "time"],
            },
        ),
    ]
